- name: Check multipass
  shell: "multipass version"
  changed_when: no

- name: Write cloud-init template
  vars:
    multipass_vm_pub_key: "{{ keypair_result.public_key }}"
  template:
    src: "cloud-init.yaml"
    dest: "{{ multipass_build_dir }}/cloud-init.yaml"
  register: cloud_init

- name: List multipass instances
  shell: "multipass list"
  changed_when: no
  register: multipass_list

- name: Check if VM needs to be created or re-created
  set_fact:
    need_delete: "{{ cloud_init.changed and (multipass_list.stdout is search(multipass_vm_name)) }}"
    need_create: "{{ cloud_init.changed or (multipass_list.stdout is not search(multipass_vm_name)) }}"

- name: Delete existing VM if cloud-init changed
  when: need_delete
  shell: "multipass delete {{ multipass_vm_name }} && multipass purge"
  failed_when: no

- name: Create VM
  shell: "multipass launch --name {{ multipass_vm_name }} --cloud-init {{ cloud_init.dest }} {{ multipass_vm_release }}"
  when: need_create

- name: Show instance details
  shell: "multipass info {{ multipass_vm_name }}"
  changed_when: no
  register: multipass_info

- name: Save VM facts
  set_fact:
    multipass_vm_address: "{{ multipass_info.stdout_lines[2] | regex_search('\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}') }}"
    multipass_vm_private_key: "{{ keypair_result.filename }}"
